// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project4._0_C3_CrowdCtrl_Back.Models;

#nullable disable

namespace Project4._0_C3_CrowdCtrl_Back.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230118075552_createDatabase")]
    partial class createDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.HasIndex("EventTypeId");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.EventType", b =>
                {
                    b.Property<int>("EventTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventTypeId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Threshold")
                        .HasColumnType("int");

                    b.HasKey("EventTypeId");

                    b.ToTable("EventType", (string)null);
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.EventUser", b =>
                {
                    b.Property<int>("EventUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventUserId"), 1L, 1);

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EventUserId");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("EventUser", (string)null);
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuardId")
                        .HasColumnType("int");

                    b.Property<int>("IncidentID")
                        .HasColumnType("int");

                    b.Property<bool>("IsAccurate")
                        .HasColumnType("bit");

                    b.HasKey("FeedbackId");

                    b.HasIndex("GuardId");

                    b.HasIndex("IncidentID");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.Group", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupID"), 1L, 1);

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZoneID")
                        .HasColumnType("int");

                    b.HasKey("GroupID");

                    b.HasIndex("EventID");

                    b.HasIndex("ZoneID");

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.GroupGuard", b =>
                {
                    b.Property<int>("GroupGuardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupGuardId"), 1L, 1);

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("GuardId")
                        .HasColumnType("int");

                    b.HasKey("GroupGuardId");

                    b.HasIndex("GroupId");

                    b.HasIndex("GuardId");

                    b.ToTable("GroupGuard", (string)null);
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentId"), 1L, 1);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordingDeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IncidentId");

                    b.HasIndex("EventId");

                    b.HasIndex("RecordingDeviceId");

                    b.ToTable("Incident", (string)null);
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.RecordingDevice", b =>
                {
                    b.Property<int>("RecordingDeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordingDeviceId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("RecordingDeviceId");

                    b.HasIndex("ZoneId");

                    b.ToTable("RecordingDevice", (string)null);
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LastName")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.Zone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZoneId");

                    b.ToTable("Zone", (string)null);
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.Guard", b =>
                {
                    b.HasBaseType("Project4._0_C3_CrowdCtrl_Back.Models.User");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Guard", (string)null);
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.Event", b =>
                {
                    b.HasOne("Project4._0_C3_CrowdCtrl_Back.Models.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.EventUser", b =>
                {
                    b.HasOne("Project4._0_C3_CrowdCtrl_Back.Models.Event", "Event")
                        .WithMany("EventUsers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project4._0_C3_CrowdCtrl_Back.Models.User", "User")
                        .WithMany("EventUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.Feedback", b =>
                {
                    b.HasOne("Project4._0_C3_CrowdCtrl_Back.Models.Guard", "Guard")
                        .WithMany()
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project4._0_C3_CrowdCtrl_Back.Models.Incident", "Incident")
                        .WithMany("Feedbacks")
                        .HasForeignKey("IncidentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guard");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.Group", b =>
                {
                    b.HasOne("Project4._0_C3_CrowdCtrl_Back.Models.Event", "Event")
                        .WithMany("Groups")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project4._0_C3_CrowdCtrl_Back.Models.Zone", "Zone")
                        .WithMany("Groups")
                        .HasForeignKey("ZoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.GroupGuard", b =>
                {
                    b.HasOne("Project4._0_C3_CrowdCtrl_Back.Models.Group", "Group")
                        .WithMany("GroupGuards")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project4._0_C3_CrowdCtrl_Back.Models.Guard", "Guard")
                        .WithMany("GroupGuards")
                        .HasForeignKey("GuardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Guard");
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.Incident", b =>
                {
                    b.HasOne("Project4._0_C3_CrowdCtrl_Back.Models.Event", "Event")
                        .WithMany("Incidents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project4._0_C3_CrowdCtrl_Back.Models.RecordingDevice", "RecordingDevice")
                        .WithMany("Incidents")
                        .HasForeignKey("RecordingDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("RecordingDevice");
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.RecordingDevice", b =>
                {
                    b.HasOne("Project4._0_C3_CrowdCtrl_Back.Models.Zone", "Zone")
                        .WithMany("Devices")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.Guard", b =>
                {
                    b.HasOne("Project4._0_C3_CrowdCtrl_Back.Models.User", null)
                        .WithOne()
                        .HasForeignKey("Project4._0_C3_CrowdCtrl_Back.Models.Guard", "UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.Event", b =>
                {
                    b.Navigation("EventUsers");

                    b.Navigation("Groups");

                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.Group", b =>
                {
                    b.Navigation("GroupGuards");
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.Incident", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.RecordingDevice", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.User", b =>
                {
                    b.Navigation("EventUsers");
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.Zone", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Project4._0_C3_CrowdCtrl_Back.Models.Guard", b =>
                {
                    b.Navigation("GroupGuards");
                });
#pragma warning restore 612, 618
        }
    }
}
